### ISSUE TITLE
version 2.1.1.0: error: undefined method ageAtEvent()

### ISSUE THREAD

**Issue by arbor95** [huhwt/huhwt-xtv#9]
Call to undefined method Fisharebest\Webtrees\Age::ageAtEvent() …/modules_v4/huhwt-xtv/Traits/ModuleChartTrait.php:78
#0 …/modules_v4/huhwt-xtv/InteractiveTreeXT.php(297): HuHwt\WebtreesMods\InteractiveTreeXT\InteractiveTreeXT->chartSubTitle()
#1 …/app/Http/RequestHandlers/ModuleAction.php(85): HuHwt\WebtreesMods\InteractiveTreeXT\InteractiveTreeXT->getChartAction()

**Comment by arbor95** [comment]
thx for fixing
